config/routes.rb
Games4trade::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "session/new"

  get "session/create"

  get "session/destroy"

  get "session/signin"

  get "session/signout"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'
  
  resources :users do
    member do
      get :repository, :wishlist, :admin
    end
  end
  
  
  resources :games
  resources :repository_items
  resources :wishlist_items

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/sessions',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  
  
  match '/repository/destroy/:id',  :to => 'repository_items#destroy', :as => :destroy_repository_item
  match '/repository/:id',  :to => 'repository_items#create', :as => :create_repository_item
  match '/wishlist/destroy/:id',  :to => 'wishlist_items#destroy', :as => :destroy_wishlist_item
  match '/wishlist/:id',  :to => 'wishlist_items#create', :as => :create_wishlist_item

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :repository_items, :dependent => :destroy
  has_many :wishlist_items, :dependent => :destroy
  
  has_many :repository_games, :through => :repository_items, :source => :game
  has_many :wishlist_games, :through => :wishlist_items, :source => :game
  
  
  has_many :buys, :class_name => "Sell", :dependent => :destroy, :foreign_key => "buyer_id"
  has_many :sells, :through => :repository_items, :source => :sell
  has_many :reputations, :dependent => :destroy, :foreign_key => "reputed_id"
  
  
	validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
                       
                       

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => true

  before_save :encrypt_password
  
	def self.search(search)
	  if search
		where('name LIKE ?', "%#{search}%")
	  else
		scoped
	  end
	end
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def points
  	pts = 0
  	self.reputations.each{ |reputation| pts=pts+reputation.points }
  	pts
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def hasRepositoryGame?(game)
  	repository_items.find_by_game_id(game.id)
  end

  def hasWishlistGame?(game)
  	wishlist_items.find_by_game_id(game.id)
  end
  
  def newRepositoryGame!(game)
    repository_items.create!(:game_id => game.id)
  end
  
  def newWishlistGame!(game)
    wishlist_items.create!(:game_id => game.id)
  end
  
  def removeRepositoryGame!(game)
  	repository_items.find_by_game_id(game.id).destroy
  end
  
  def removeWishlistGame!(game)
  	wishlist_items.find_by_game_id(game.id).destroy
  end
  
  def toggleAdmin!
  	self.toggle!(:admin)
  end
  
  def findSell(game)
  	item = repository_items.find_by_game_id(game.id)
  	item.sell unless item.nil?
  end
  
  private
	def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy, :show, :wishlist, :repository, :admin]
  before_filter :correct_user, :only => [:edit, :update, :wishlist, :repository]
  before_filter :admin_user,   :only => [:destroy, :admin]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.search(params[:search]).paginate(:page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
	@title = @user.name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
	
    @title = "Sign up"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
	    sign_in @user
        format.html { redirect_to @user, success: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  
  
  def wishlist
    @title = t("Wishlist")
    @h1title = t("Wishlist games")
    @user = User.find(params[:id])
    @games = @user.wishlist_games.paginate(:page => params[:page])
    render 'games/index'
  end

  def repository
    @title = t("Repository")
    @h1title = t("Repository games")
    @user = User.find(params[:id])
    @games = @user.repository_games.paginate(:page => params[:page])
    render 'games/index'
  end
  
  def admin
    @user = User.find(params[:id])
	respond_to do |format|
      if @user.toggleAdmin!
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  	
  
end

app/helpers/users_helper.rb
module UsersHelper


  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_form.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %> 

<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  </fieldset>
  <fieldset>
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.text_field :birth_date %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :complement %><br />
    <%= f.text_field :complement %>
  </div>  
  </fieldset>
  <div class="actions">
    <%= f.submit(t("Submit")) %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%=t "Editing user"%></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1><%=t "All users"%></h1>

<%= form_tag users_path, :method => 'get', :id => "users_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= will_paginate @users %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, user %>
      <%= user.email %>
      <%= user.points %>
      <% if current_user.admin? %>
	  | <%= link_to t("delete"), user, :method => :delete, :confirm => "You sure?",
		                            :title => "Delete #{user.name}" %>
      | <%= link_to (!user.admin? ? t("promote") : t("unpromote")), :controller => "users", :action => :admin, :id => user, :confirm => "You sure?",
        	:title => "Delete #{user.name}" %>
	  <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate @users %>

<br />

app/views/users/new.html.erb
<h1><%=t "Sign up" %></h1>

<%= render 'form' %>

<%= link_to t('Back'), users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= gravatar_image_tag @user.email %>
  <%= @user.name %></br>

  <%=t :name %>:
  <%= @user.name %></br>
  <%=t :email %>:
  <%= @user.email %></br>
  <%=t :city %>:
  <%= @user.city %></br>
  <%=t :state %>:
  <%= @user.state %></br>
  <%=t :admin if @user.admin? %>
</h2>

<fieldset>
  <legend><%=t "Stats" %>:</legend>
  <%= render 'shared/stats' %>
</fieldset>


<fieldset>
  <legend><%=t "Game in Repository" %>:</legend>
  <% @user.repository_games.each do |game| %></br>
	<%= link_to game.name, game %>
  <% end %>
</fieldset>

<fieldset>
  <legend><%=t "Game in Wishlist" %>:</legend>
  <% @user.wishlist_games.each do |game| %></br>
	<%= link_to game.name, game %>
  <% end %>
</fieldset>

app/views/users/show_games.html.erb
<table summary="Information about games">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, :size => 30), user %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>