config/routes.rb
Games4trade::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "session/new"

  get "session/create"

  get "session/destroy"

  get "session/signin"

  get "session/signout"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'
  
  resources :users do
    member do
      get :repository, :wishlist, :admin
    end
  end
  
  
  resources :games
  resources :repository_items
  resources :wishlist_items

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/sessions',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  
  
  match '/repository/destroy/:id',  :to => 'repository_items#destroy', :as => :destroy_repository_item
  match '/repository/:id',  :to => 'repository_items#create', :as => :create_repository_item
  match '/wishlist/destroy/:id',  :to => 'wishlist_items#destroy', :as => :destroy_wishlist_item
  match '/wishlist/:id',  :to => 'wishlist_items#create', :as => :create_wishlist_item

end

app/views/shared/_stats.html.erb
<% @user ||= current_user if @user.nil?%>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= wishlist_user_path(@user) %>">
          <span id="wishlist" class="stat">
            <%= @user.wishlist_items.count %> <%=t "games in the wishlist" %>
          </span>
        </a>
      </td>
      <td>
        <a href="<%= repository_user_path(@user) %>">
          <span id="repository" class="stat">
          	<%= @user.repository_items.count %> <%=t "games in the repository" %>
          </span>
        </a>
      </td>
    </tr>
  </table>
  <h3><%=t "Total Reputation Points: "%><%= @user.points %></h3>
  <ul>
  <% @user.reputations.each do |reputation| %>
	  <li>
	  <b><%= reputation.reputer.name %>: </b>(<%= reputation.points %>): <%= reputation.review %>
	  </li>
  <% end %>
  </ul>
</div>