config/routes.rb
Games4trade::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "session/new"

  get "session/create"

  get "session/destroy"

  get "session/signin"

  get "session/signout"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'
  
  resources :users do
    member do
      get :repository, :wishlist, :admin
    end
  end
  
  
  resources :games
  resources :repository_items
  resources :wishlist_items

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/sessions',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  
  
  match '/repository/destroy/:id',  :to => 'repository_items#destroy', :as => :destroy_repository_item
  match '/repository/:id',  :to => 'repository_items#create', :as => :create_repository_item
  match '/wishlist/destroy/:id',  :to => 'wishlist_items#destroy', :as => :destroy_wishlist_item
  match '/wishlist/:id',  :to => 'wishlist_items#create', :as => :create_wishlist_item

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :repository_items, :dependent => :destroy
  has_many :wishlist_items, :dependent => :destroy
  
  has_many :repository_users, :through => :repository_items, :source => :user
  has_many :wishlist_users, :through => :wishlist_items, :source => :user

	def self.search(search)
	  if search
    	where('name LIKE ?', "%#{search}%")
	  else
    	scoped
	  end
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :admin_user,   :only => [:new, :create, :edit, :update, :destroy]
  # GET /games
  # GET /games.json
  def index
    @games = Game.search(params[:search]).paginate(:page => params[:page])#:per_page => 5,   .order(sort_column + " " + sort_direction)
    @h1title = t("All games")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
  
  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %> 

<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
  </div>
  <div class="field">
	<%= f.label :plataform %><br />
	<%= f.select(:plataform, ["Windows x86", "Windows AMD64", "Playstation 3", "Playstation 2", "Xbox 360", "Wii", "Linux", "MaxOS"]) %>
  </div>
  <div class="field">
	<%= f.label :media_type %><br />
	<%= f.select(:media_type, ["CD", "DVD", "Pendrive", "Download"]) %>
  </div>
  <div class="field">
	<%= f.label :media_count %><br />
	<%= f.text_field :media_count, {:type => :number} %>
  </div>
  <div class="field">
	<%= f.label :genre %><br />
	<%= f.select(:genre, ["Action", "Arcade", "FPS", "RPG", "RTS", "Horror", "MMoRPG", "Casual"]) %>
  </div>
  <div class="field">
	<%= f.label :review %><br />
	<%= f.text_area :review %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1><%=t "Editing game" %></h1>

<%= render 'form' %>

<%= link_to t('Show'), @game %> |
<%= link_to t('Back'), games_path %>

app/views/games/index.html.erb
<h1><%= @h1title %></h1>

<%= form_tag games_path, :method => 'get', :id => "games_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= will_paginate @games %>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
	<% if signed_in? %>
    <th></th>
    <th></th>
	<% if current_user.admin? %>
    <th></th>
    <th></th>
	<% end %>
	<% end %>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.name %></td>
    <td><%= game.plataform %></td>
	<td><%= game.media_count %> <%= game.media_type %></td>
    <td><%= game.genre %></td>
    <td><%= link_to t('Show'), game %></td>
	<% if signed_in? %>
    <td>
<% if current_user.hasRepositoryGame?(game) %>
    <%= t("In Repository") %>
	<%= link_to t('x'), destroy_repository_item_path(game)%>
<% else %>
	<%= link_to t('Add to Repository'), create_repository_item_path(game)%>
<% end %>
	</td>
    <td>
<% if current_user.hasWishlistGame?(game) %>
    <%= t("In Wishlist") %>
	<%= link_to t('x'), destroy_wishlist_item_path(game)%>
<% else %>
	<%= link_to t('Add to Wishlist'), create_wishlist_item_path(game)%>
<% end %>
	</td>
	<% if current_user.admin? %>
    <td><%= link_to t('Edit'), edit_game_path(game) %></td>
    <td><%= link_to t('Destroy'), game, confirm: 'Are you sure?', method: :delete %></td>
	<% end %>
	<% end %>
  </tr>
<% end %>
</table>

<%= will_paginate @games %>
<br />

<% if signed_in? && current_user.admin? %>
<%= link_to t('New Game'), new_game_path %>
<% end %>

app/views/games/new.html.erb
<h1><%=t "New game" %></h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%=t :name %>:
  <%= @game.name %></br>
  
  
  <%=t :plataform %>:
  <%= @game.plataform %></br>
  
  <%=t :media_type %>:
  <%= @game.media_count %> <%= @game.media_type %></br>
  
  <%=t :genre %>:
  <%= @game.genre %></br>

</h2>

<h3>
  <%=t :review %>:
  <%= @game.review %></br>
</h3>


<fieldset>
  <legend><%=t "Who has this game in its Repository" %>:</legend>
  <% @game.repository_users.each do |user| %></br>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	<%= user.email %>
	<% sell = user.findSell(@game) %>
	<% if (!sell.nil?) %>
	<%= sell.value %>
	<% end %>
  <% end %>
</fieldset>

<fieldset>
  <legend><%=t "Who has this game in its Wishlist" %>:</legend>
  <% @game.wishlist_users.each do |user| %></br>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	<%= user.email %>
  <% end %>
</fieldset>



<% if signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_game_path(@game) %> |
<% end %>
<%= link_to 'Back', games_path %>