config/routes.rb
Games4trade::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "session/new"

  get "session/create"

  get "session/destroy"

  get "session/signin"

  get "session/signout"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'
  
  resources :users do
    member do
      get :repository, :wishlist, :admin
    end
  end
  
  
  resources :games
  resources :repository_items
  resources :wishlist_items

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/sessions',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  
  
  match '/repository/destroy/:id',  :to => 'repository_items#destroy', :as => :destroy_repository_item
  match '/repository/:id',  :to => 'repository_items#create', :as => :create_repository_item
  match '/wishlist/destroy/:id',  :to => 'wishlist_items#destroy', :as => :destroy_wishlist_item
  match '/wishlist/:id',  :to => 'wishlist_items#create', :as => :create_wishlist_item

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>    
      <li><%= link_to t("Home"), root_path %></li>
      <li><%= link_to t("Help"), help_path %></li>
      <li><%= link_to t("Games"), games_path %></li>
      <% if signed_in? %>
      <li><%= link_to t("Users"), users_path %></li>
      <li><%= link_to t("Profile"), current_user %></li>
      <li><%= link_to t("Settings"), edit_user_path(current_user) %></li>
      <li><%= link_to t("Sign out"), signout_path %></li>
      <% if current_user.admin? %>
      <li><%= "Master" %></li>
      <% end %>
      <% else %>
      <li><%= link_to t("Sign in"), signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
	<%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>